### ISSUE TITLE
AT is not parsed correctly

### ISSUE THREAD

**Issue by ginuerzh** [suyashkumar/dicom#143]
AT(Attribute Tag) is an ordered pair of 16-bit unsigned integers, so it should not be treated as a simple string. I think it can be parsed as uint32 or a formatted string (e.g. '0x00020001', '0002,0001').

**Comment by suyashkumar** [comment]
Thanks for raising this! Yes, I agree we should parse this VR as an ordered pair of 16-bit integers. This appears to be very similar to a data element tag, so it's possible we can store it in the same container (also it appears that semantically it often refers to a data element tag).

Would you be interested in contributing a fix? If not, I can probably get to it this weekend or next weekend :). 

Cheers!

**Comment by ginuerzh** [comment]
I prefer to decode it into uint32, if you can accept it, I will create a PR this week.

**Comment by suyashkumar** [comment]
@ginuerzh we would want to parse it into a [`ValueType`](https://godoc.org/github.com/suyashkumar/dicom#ValueType) for it to fit into the framework. Currently, I parse uints into higher-level Go integers which are easier to work with. So that is one option to at least start out with!

From there, a caller can always convert back to uints or a `Tag` struct as needed.

Feel free to contribute a fix if you would like, happy to accept contributions! I can also contribute a fix sometime this week too.
