### ISSUE TITLE
De-identify DICOM tags

### ISSUE THREAD

**Issue by vijaysubramanya** [suyashkumar/dicom#237]
I'm trying to update/de-identify some of the metadata tags (such as Patient ID). Is there a way to update the file directly without reading the file and writing back to the file? Currently, I'm reading the file into a variable, updating the elements, and writing back to a new file as below:

```
dataset, _ := dicom.ParseFile("dicom/1.dcm", nil)
    for _, elem := range dataset.Elements {
        s := reflect.TypeOf(elem.Value.GetValue()).Kind()
        if s == reflect.Slice {
            elem.Value, _ = dicom.NewValue([]string{"abc"})
        }
    }
    f, err := os.Open("test.dcm")
    err = dicom.Write(f, dataset)
    }
```

**Comment by vijaysubramanya** [comment]
@suyashkumar @jstutters

**Comment by suyashkumar** [comment]
Hi there! At the moment, I'm not sure of a great way to safely update the file "in place" if that's what you want. 

Something I would like to do is update the element-by-element parsing API (e.g. the [Next() API on the parser](https://github.com/suyashkumar/dicom/blob/58fd583d8e5ad40e8d40aa463b6e88f30f9b1308/parse.go#L163)) be more memory efficient by _only_ holding onto the Dataset elements it needs for future parsing, and otherwise just transiently emitting the Elements one at a time.

**Comment by suyashkumar** [comment]
Closing this, as I think the question was answered re: in-place editing.
