### ISSUE TITLE
ERROR: too many open files

### ISSUE THREAD

**Issue by IChocked** [suyashkumar/dicom#75]
Results after too many dicom files (in my case 1024) have attempted to be opened and failed. 

The issue seems to results from the function `NewParserFromFile()` in Parse.go. Each time the function is called, it opens a new file, but that file is not closed in the function or the termination of the function, but rather is indirectly closed later by the code execution following `p.(*parser).file = file`. The result of this is that files that incur an error are never closed because they return before that line, and once the max number of errored files are open, the program spits out this error for every subsequent file.

I'm in the process of submitting a fix. I'll add a pull request soon.

**Comment by suyashkumar** [comment]
Thanks for the upcoming contribution! Agreed, if there are other errors in NewParserFromFile, the file should be closed before returning

**Comment by wkoszek** [comment]
@IChocked For the fix, if we don't use `.file` variable anymore, feel free to remove it from the Parser structure.

**Comment by suyashkumar** [comment]
Commented on the PR #76, I think we should be careful about trying to read the file all at once, and instead should continue to use the buffered `io.Reader` API (for example, consider reading large files from a network filesystem). This will ensure that the streaming of frames as they are parsed is still functional. I think we should certainly close the file if NewParserFromFile returned with an error though! 

Also, perhaps it's worth not adding this in the 1.0 API, and simply leaving the [io.Reader interface](https://github.com/suyashkumar/dicom/blob/s/1.0-rewrite/parse.go), forcing the caller to manage the source of the data (files, closing them, etc).

Though it's not the worst for the caller to do something like:
```go
p, err := dicom.NewParserFromFile(...)
if err != nil {
  // handle
}
defer p.Finish()  // caller may want to handle this error as well
```

The main reason this is in there is to support the ParseNext API, but I agree it's a little clunky to be managing the file on our end.

Since Parse already calls p.Finish, to adhere cleanly to the pattern above we may need to put some guards in place in case p.Finish is called multiple times (haven't looked too closely at this).

**Comment by wkoszek** [comment]
@suyashkumar I'm ok with @IChocked simple change (closing file). I like the idea of passing the reader interface for v1.0

**Comment by suyashkumar** [comment]
Sounds good! Note that the [existing API](https://github.com/suyashkumar/dicom/blob/8abd37b0527758076982254a1862c972aeb6e1c8/parse.go#L43) also does allow a user to call `NewParser` and supply an io.Reader, but the `NewParserFromFile` was added as a convenience method, which perhaps we'll consider leaving out in the 1.0 API.
