### ISSUE TITLE
ERROR ReadBytes

### ISSUE THREAD

**Issue by IChocked** [suyashkumar/dicom#77]
`ERROR ReadBytes: requested 2, available 0 (file offset 65274)`

I haven't had a chance to look into it yet, but I've attached 3 example files and will try to get more info sometime soon.

[examples.zip](https://github.com/suyashkumar/dicom/files/4665083/examples.zip)

Data Citation:
_Kinahan, Paul; Muzi, Mark; Bialecki, Brian; Coombs, Laura. (2017). Data from ACRIN-FLT-Breast. The Cancer Imaging Archive. http://doi.org/10.7937/K9/TCIA.2017.ol20zmxg_

**Comment by suyashkumar** [comment]
Fantastic, thank you for raising this and posting some sample files! Will see if I can investigate a little this weekend or later next week, and let me know if you have a chance to investigate in the meantime. It might be nice to also try the rewritten parser on this set of files as well. I think we should also consider adding in more robust debug instrumentation throughout the parser, both the current one and the rewritten one (will open a feature request for that)

**Comment by suyashkumar** [comment]
I have done some quick investigation, and I think I see what the issue is. 

It looks like the PixelData tag `(7FE0,0010)` can appear multiple times in a Dataset, in particular when it is part of an Icon Image Sequence.

In this case, when we parse that native pixel data, we must make use of tags that have appeared earlier (like `Rows`, `BitsAllocated`, etc). However, if we encounter the PixelData tag within an Icon Image Sequence, we need to fetch these tags from within the current sequence instead of from the global dataset. If we fetch them from the global dataset, we end up grabbing the values for the actual PixelData and not the icon!

Will look into a mitigation for this shortly. Will also keep this in mind for the rewrite. This only seems to be an issue for the native pixel data, which AFAIK is the main thing that requires looking back at the dataset to parse (encapsulated pixel data does not require "looking back"). 

The Rows tag is 

(0028,0010)
--

**Comment by suyashkumar** [comment]
You can see the WIP draft PR #79 that should quick fix this, and appears to work for the provided DICOMs (thanks again for those). There is one odd thing that I'd like to check out before merging, and maybe refactor to avoid some temporary copies either now or in a follow up PR.
