### ISSUE TITLE
Incorrect error "VR value mismatch for tag (0028,0120)[PixelPaddingValue]. Element.VR=SS, but DICOM standard defines VR to be US"

### ISSUE THREAD

**Issue by courteouselk** [suyashkumar/dicom#91]
We receive this error when we try write down a DICOM file we have just parsed and slightly updated:

> dicom.Element: VR value mismatch for tag (0028,0120)[PixelPaddingValue]. Element.VR=SS, but DICOM standard defines VR to be US

However, the standard defines both `US` and `SS` to be valid values.  E.g. see: [DICOM PS3.6 2020c - Data Dictionary](http://dicom.nema.org/medical/dicom/current/output/html/part06.html) or  [Pixel Padding Value Attribute](https://dicom.innolitics.com/ciods/rt-plan/general-equipment/00280120).

**Comment by suyashkumar** [comment]
Thank you for reporting this! 

I haven't done much with the write package since inheriting from the upstream fork (by contrast much of the read package is [being rewritten](https://github.com/suyashkumar/dicom/tree/s/1.0-rewrite), and the write package should be too at some point imo). 

This is happening because right now only one VR is read in from the dicom standard into the tag map: https://github.com/suyashkumar/dicom/blob/9d8d8d93103033c11b791381ffe54559ce4c7429/dicomtag/tag_definitions.go#L3369

Likely after some rewrites we should ingest multiple possible values for the padding.

For now, one option is to skip the VR verification during writing: https://github.com/suyashkumar/dicom/blob/9d8d8d93103033c11b791381ffe54559ce4c7429/write/writer.go#L22

While this doesn't solve the validation, is this option sufficient for you?

**Comment by courteouselk** [comment]
Hi @suyashkumar, thanks for the prompt reply.  I had a look at the possibility to use that option and it seems that we could try to use it.  There is just one minor problem, we use `write.DataSetToFile` call, and this one has a bug of not passing `opts` argument to subsequent `write.DataSet` call.  I had just pushed a PR to fix this (one-liner).

**Comment by suyashkumar** [comment]
@courteouselk thank you! Merged #102, and will add a tagged version later today.

**Comment by suyashkumar** [comment]
@courteouselk the v0.4.5 tagged version includes your fix, thank you! Closing this out.
